// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnKw6QCEv_p1hvpF7MMaW2jH_V5bEYV2o',
    appId: '1:269823588068:web:e7be6dce4212c570d6def1',
    messagingSenderId: '269823588068',
    projectId: 'sewatani-fasido-2403107',
    authDomain: 'sewatani-fasido-2403107.firebaseapp.com',
    storageBucket: 'sewatani-fasido-2403107.firebasestorage.app',
    measurementId: 'G-QJ4X4GWQN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACztBvWD3jxsGnlS7tBeJ4qOF8qKu7D4',
    appId: '1:269823588068:android:f423367fee3d08ead6def1',
    messagingSenderId: '269823588068',
    projectId: 'sewatani-fasido-2403107',
    storageBucket: 'sewatani-fasido-2403107.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5IgwstXysiMIt3yqC4Ub8wah2Z6gYBTE',
    appId: '1:269823588068:ios:9427373480b5ba8bd6def1',
    messagingSenderId: '269823588068',
    projectId: 'sewatani-fasido-2403107',
    storageBucket: 'sewatani-fasido-2403107.firebasestorage.app',
    androidClientId: '269823588068-dsuh93bu7al9i11pkgq18o7v7bt0brhv.apps.googleusercontent.com',
    iosClientId: '269823588068-n7ig0lrr48p0ctgdenatgdo31rgr6lqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileSewatani',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5IgwstXysiMIt3yqC4Ub8wah2Z6gYBTE',
    appId: '1:269823588068:ios:9427373480b5ba8bd6def1',
    messagingSenderId: '269823588068',
    projectId: 'sewatani-fasido-2403107',
    storageBucket: 'sewatani-fasido-2403107.firebasestorage.app',
    androidClientId: '269823588068-dsuh93bu7al9i11pkgq18o7v7bt0brhv.apps.googleusercontent.com',
    iosClientId: '269823588068-n7ig0lrr48p0ctgdenatgdo31rgr6lqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileSewatani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnKw6QCEv_p1hvpF7MMaW2jH_V5bEYV2o',
    appId: '1:269823588068:web:7af52f4cc8bc976bd6def1',
    messagingSenderId: '269823588068',
    projectId: 'sewatani-fasido-2403107',
    authDomain: 'sewatani-fasido-2403107.firebaseapp.com',
    storageBucket: 'sewatani-fasido-2403107.firebasestorage.app',
    measurementId: 'G-GYDJSSXS22',
  );
}
