name: mobile_sewatani
description: "Aplikasi mobile penyewaan alat pertanian SewaTani untuk petani dan vendor di Indramayu."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.5+1

  # Local session storage
  shared_preferences: ^2.5.5

  # API request ke backend PHP/MySQL
  http: ^1.6.0

  # Firebase & Google Login
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  google_sign_in: ^7.2.0

  # Firebase Cloud Messaging
  firebase_messaging: ^16.3.0

  # Format tanggal dan rupiah
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/